### PR TITLE
aunit: add output format sonar

### PR DESCRIPTION
**Pull request by corani**
This addresses #26 
I don't recommend merging this, as it's a bit hacky. But perhaps it could be a starting point.

### CODE REVIEW

**Comment by corani** [comment]
This addresses #26

**Comment by jfilak** [comment]
@corani Aaaaawesome! Would you mind adding a test case to https://github.com/jfilak/sapcli/blob/master/test/unit/test_sap_cli_aunit.py ? You can copy https://github.com/jfilak/sapcli/blob/master/test/unit/test_sap_cli_aunit.py#L129

**Comment by jfilak** [comment]
@corani Do you really need an existing file? Could it be a made up file?

**Comment by corani** [comment]
Sonar uses it to decorate the original source files. Not sure about what they do with the executions, but they definitely do so for the coverage.

We'd probably need some utility method to match up the files, instead of this...

Sure, if you want to take this PR further, I'll add a unit test.

**Comment by jfilak** [comment]
In the end, if a user does not add the parameter `--output sonar`, your code will not be executed, so I think we can merge it if you add the unit tests.

I think the documentation should include the information that `sonar` output requires `sapcli checkout` (or git clone of the corresponding abapGit repo) and the command must be executed in the repo directory.

We can think up a way how to pass parameters to your formatter. I would not be against single purpose command line options used just by your formatter.

**Comment by corani** [comment]
Added documentation and unit tests. I'm not sure if stack traces in "tolerable" alerts are a thing, so I haven't added a test fixture for those. I'm also not testing the file path resolution, just using the synthetic names in the test cases.

**Comment by jfilak** [comment]
Good job. Thank you!

**Pull request merged**
