### PR TITLE
gcts: extend activities filter options

### PR DESCRIPTION
**Pull request by palubaj**
Added a new type of activity that can be used to filter list of activities.

### CODE REVIEW

**Comment by jfilak** [comment]
@palubaj what is the relation between CHECKOUT and BRANCH_SW?

**Comment by palubaj** [comment]
> @palubaj what is the relation between CHECKOUT and BRANCH_SW?

I could not find any specific documentation on the activity types. The best I found was [this]( https://help.sap.com/docs/ABAP_PLATFORM_NEW/4a368c163b08418890a406d413933ba7/fe2608030adc4548b9d47c8dfc8fe434.html?version=201909.000). But from the GCTS API documentation I found out that the only way to change active branch is using `/repository/{id}/branches/{id}/switch` endpoint (the `BRANCH_SW` is triggered only when switching to remote branch). Hence, it seems that the `CHECKOUT` activity does not exist.

Should I remove it completely?

**Comment by jfilak** [comment]
It does not look nice:
image

**Comment by jfilak** [comment]
The source is:
image

**Comment by jfilak** [comment]
The parameter TYPE of CL_CTS_ABAP_VCS_REPOSITORY=>ADD_HISTORY( ) is SCTS_ABAP_VCS_HISTORY_TYPE (the storage is the table SCTS_AVCS_REPHIS) but most of the time, we pass the result of IF_CTS_ABAP_VCS_COMMIT=>GET_TYPE( ) which is SCTS_ABAP_VCS_COMMIT_TYPE.

**Comment by jfilak** [comment]
Sometimes, the history is directly filled with one of the following constant:
image

**Comment by jfilak** [comment]
Bottom line: Drop CHECKOUT as I cannot see it anywhere. Add comments where to find the constants to the code so we do not need to do it the hardway next time (I would also make some notes in documentation).

**Comment by jfilak** [comment]
Thank you!

**Pull request merged**
