### PR TITLE
Adding ATC Filter Parameter

### PR DESCRIPTION
**Pull request by lucasborin**
Implements #81.

With filter:
`./sapcli atc run class my_class`

```
* 2 :: Package Check  (SLIN_PAC) :: Package Violation (Error) - Missing Use Access (USEM)
* 2 :: Package Check  (SLIN_PAC) :: Package Violation (Error) - Missing Use Access (USEM)
* 2 :: Package Check  (SLIN_PAC) :: Package Violation (Error) - Missing Use Access (USEM)
* 2 :: Package Check  (SLIN_PAC) :: Package Violation (Error) - Missing Use Access (USEM)
* 2 :: Package Check  (SLIN_PAC) :: Package Violation (Error) - Missing Use Access (USEM)
* 1 :: Syntax Check Warnings  (SLIN_SYWRN) :: Method was not implemented (W017)
```

With filter:
`./sapcli atc run class my_class -f 1`

```
* 1 :: Syntax Check Warnings  (SLIN_SYWRN) :: Method was not implemented (W017)
```

### CODE REVIEW

**Comment by lucasborin** [comment]
@jfilak: Would it make sense? I need it.

**Comment by lucasborin** [comment]
If you do not mind...

image

Ref: https://hacktoberfest.com/

**Comment by jfilak** [comment]
@lucasborin  I have added the hactoberfest label.

**Comment by jfilak** [comment]
@lucasborin The code looks ok but I am not sure about the names. The parameter "-a" does not sound right and atc_filter neither. Could you please try finding more specific names?

**Comment by jfilak** [comment]
Please add tests to https://github.com/jfilak/sapcli/blob/master/test/unit/test_sap_cli_atc.py

**Comment by lucasborin** [comment]
@jfilak could you please check again? 

Ps: UTs are not working here due to bad IDE configuration.

**Comment by lucasborin** [comment]
@jfilak - All fixed. Good to go for review.

**Comment by jfilak** [comment]
Good job!

**Pull request merged**
