### PR TITLE
ABAP Unit - JUnit4 Format Improvements for GitHub Jenkins integration

### PR DESCRIPTION
**Pull request by lucasborin**
New format to display aunit results in GitHub Pull Requests.

image

Based on [JUnit4 ](https://llg.cubic.org/docs/junit/) layout.

### CODE REVIEW

**Comment by lucasborin** [comment]
If someone is using this JUnit4, we can consider having a new formatter like `Jenkins`.

**Comment by jfilak** [comment]
> If someone is using this JUnit4, we can consider having a new formatter like Jenkins.

Do I get it right that the changes you have been working on are good for Jenkins but not so good for those who use use other JUnit processors (viewers)? If so, I agree you should rather add a new formatter called "JUnit4AUnit"  :)

Please, add a also screenshots from Jenkins Job OceanBlue Tests overview. I do remember  I tailored the current JUnit output for that JUnit viewer.


BTW, please update also the documentation at:
https://github.com/jfilak/sapcli/blob/master/doc/commands/aunit.md#junit

**Comment by lucasborin** [comment]
Looks good to go. @jfilak, do you want to review?

**Comment by jfilak** [comment]
@lucasborin  Have you closed this PR intentionally?

**Pull request closed without merging**
